# Generated by Django 5.1.15 on 2026-02-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=100)),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("venda", "Venda"),
                            ("compra", "Compra"),
                            ("aluguel", "Aluguel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tipo_imovel",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("kitnet", "KitNet"),
                            ("salao", "Salão"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("area", models.PositiveIntegerField()),
                ("quartos", models.PositiveIntegerField()),
                ("cidade", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("publicado", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "foto_imovel",
                    models.ImageField(
                        blank=True, null=True, upload_to="imoveis/fotos/%Y/%m/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("editado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
